### ISSUE TITLE
Cannot run test (git commit: 1261e57)

### ISSUE THREAD

**Issue by kerbymart** [arquillian/arquillian-extension-gwt#3]
Error when running $mvn test 

Results :

Tests in error: 
  org.jboss.arquillian.gwt.client.test.GreeterRpcTest: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
  org.jboss.arquillian.gwt.client.test.GreeterTest: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor

Using Maven version 3.1.1 and JDK 1.7

**Comment by bartoszmajsak** [comment]
Moving to attic.
